### PR TITLE
support python 2 and 3

### PR DESCRIPTION
**Pull request by nickpell**

### CODE REVIEW

**Comment by nickpell** [comment]
@taxpon Adds compatibility for python 3

**Comment by taxpon** [comment]
@nickpell Great! Thanks for your contribution!

**Comment by nickpell** [comment]
You're welcome @taxpon 
Do you think you could make a new point release on pypi?  My team uses this package and would love to use it with python 3.

**Comment by taxpon** [comment]
@nickpell Sure! Wait for minutes!

**Comment by taxpon** [comment]
@nickpell Releases: https://pypi.python.org/pypi/pyzxcvbn/0.6.0

**Comment by nickpell** [comment]
Thank you! we are now using 0.6.0

**Pull request merged**
